### ISSUE TITLE
Can't launch game on my home computer (Windows 10)

### ISSUE THREAD

**Issue by zackles007** [MakerBox-NZ/pygame_zach#10]
when i try to launch the game from idle, it comes up with this in the shell

Traceback (most recent call last):
  File "C:\Users\Zach\Desktop\Python Things\pygame_zach\zachGame.py", line 5, in <module>
    import pygame #load pygame keywords
ModuleNotFoundError: No module named 'pygame'

i want to work on it at home, and idk how to fix this

**Comment by notklaatu** [comment]
You need to install pygame.

Open cmd and do this:

py.exe -m 'pip3 install pygame'
Or maybe
python.exe -m 'pip3 install pygame'

Then all will be well.

On 6 September 2017 3:24:43 PM NZST, zackles007 <notifications@github.com> wrote:
>when i try to launch the game from idle, it comes up with this in the
>shell
>
>Traceback (most recent call last):
>File "C:\Users\Zach\Desktop\Python Things\pygame_zach\zachGame.py",
>line 5, in <module>
>    import pygame #load pygame keywords
>ModuleNotFoundError: No module named 'pygame'
>
>i want to work on it at home, and idk how to fix this
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/MakerBox-NZ/pygame_zach/issues/10

-- 
Klaatu

**Comment by zackles007** [comment]
when i type in
py.exe -m 'pip3 install pygame'
or
python.exe -m 'pip3 install pygame'
it just says
C:\Users\Zach\AppData\Local\Programs\Python\Python36-32\python.exe: No module named 'pip3

**Comment by notklaatu** [comment]
Try

py.exe -m 'pip install pygame'



On 6 September 2017 6:27:31 PM NZST, zackles007 <notifications@github.com> wrote:
>when i type in
>py.exe -m 'pip3 install pygame'
>or
>python.exe -m 'pip3 install pygame'
>it just says
>C:\Users\Zach\AppData\Local\Programs\Python\Python36-32\python.exe: No
>module named 'pip3
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/MakerBox-NZ/pygame_zach/issues/10#issuecomment-327387718

-- 
Klaatu

**Comment by zackles007** [comment]
it tells me
No module named 'pip
when i try to type it in

**Comment by notklaatu** [comment]
You installed python 3 on this computer, yes? Not python 2¿

On 7 September 2017 8:03:59 AM NZST, zackles007 <notifications@github.com> wrote:
>it tells me
>No module named 'pip
>when i try to type it in
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/MakerBox-NZ/pygame_zach/issues/10#issuecomment-327597473

-- 
Klaatu

**Comment by zackles007** [comment]
yes python 3

**Comment by notklaatu** [comment]
...maybe it's the quotes that's causing it to fail. 

OK, let's try *this* one:

    py.exe -m pip install pygame --user

If that doesn't work, let me know, and I've got ONE more thing to try.

**Comment by zackles007** [comment]
it dosent work, it just keeps saying there is no module named pip

**Comment by notklaatu** [comment]
It would seem that you need to install pip. I don't know how it didn't get installed along with the rest of Python3, but let's fix it:

Download this Python script:
https://bootstrap.pypa.io/get-pip.py

Assume you have saved it to your Downloads folder.
Open the cmd prompt. Type

```
py.exe --version
```
to confirm the version of Python that py.exe is calling.

Assuming you get confirmation that it's 3.[something], continue with:

```
py.exe Downloads\get-pip.py
```

Or do whatever you need to do for Python to run the get-pip.py thing.

**Comment by zackles007** [comment]
this would work, but the get-pip thing runs for python 2.7 it seems, rather than 3.6, even though it says 3.6 for the py.exe version.

**Comment by notklaatu** [comment]
Cool, then do this:

```
pip install pygame
```

**Comment by zackles007** [comment]
it works now


cool cool
