### ISSUE TITLE
Scrolling

### ISSUE THREAD

**Issue by zackles007** [MakerBox-NZ/pygame_zach#4]
It's not really working too well and how I'd want it too, and back scrolling doesn't work

**Comment by zackles007** [comment]
like if it could scroll sooner, like if I reached the middle of the screen and smoother, that would be cool

**Comment by cyanidecupcake** [comment]
There are two different things happening here:

**1 Scrolling Smoother:** For some reason your indentations aren't lining up correctly any more.  I think this is related to the indentation issue you had two weeks ago and probably has more to do with a setting in IDLE than your actual code.  We should sit down together to look at your settings so this doesn't continue to happen.

In the meantime, you should make sure the if statements in this block of code line up with screen.blit.

```
    #scroll world forward
    if player.rect.x >= forwardX:
        scroll = player.rect.x - forwardX
        player.rect.x = forwardX
        for platform in platform_list:
            platform.rect.x -= scroll

    #scroll world backward
    if player.rect.x <= backwardX:
        scroll = min(1, (backwardX - player.rect.x))
        player.rect.x = backwardX
        for platform in platform_list:
            platform.rect.x += scroll

```



**2 Scroll Sooner:** Change where your game starts scrolling by altering the values of variables forwardX & backwardX.

```
forwardX = 600 #when to scroll
backwardX = 150 #when to scroll
```
