### ISSUE TITLE
Player can jump while moving left, but not right

### ISSUE THREAD

**Issue by zackles007** [MakerBox-NZ/pygame_zach#7]

**Comment by notklaatu** [comment]
In your Player ``update`` function, look at where you are evaluating gravity: 

```
            #gravity
            if self.collide_delta < 6 and self.jump_delta < 6:
                self.jump_delta = 6*2
                self.momentumY -=29 #how high to jump
                self.collide_delta +=6
                self.jump_delta += 6
```

That sets some important variables (``self.collide_delta`` and ``self.jump_delta``).

Maybe that is affecting calculations happening later in the update function.

If I'm being too vague, ask me for help in class, but see if you can see the problem from what I've said here.

**Comment by Coinmat3r** [comment]
Move the entire block of code down to the bottom on def update

**Comment by notklaatu** [comment]
I believe this has been solved. If so, close this issue.
